package br.org.acal.application.telas;

import br.org.acal.resouces.dao.DaoContasMensais;
import br.org.acal.resouces.entidades.Conta;
import br.org.acal.resouces.entidades.Taxasconta;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class GContasAReceber extends JFrame {

    private JFrame telaPrincipal;
    public GContasAReceber() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public GContasAReceber(JFrame telaPrincipal){   
        this();
        jButtonPagar.setEnabled(false);
        this.telaPrincipal = telaPrincipal;
        this.telaPrincipal.setEnabled(false);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jTextFieldPesquisa = new JTextField();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        jLabel6 = new JLabel();
        jFormattedTextFieldDataGerada = new JFormattedTextField();
        jLabel2 = new JLabel();
        jFormattedTextFieldDataPagamento = new JFormattedTextField();
        jLabel5 = new JLabel();
        jTextFieldSocio = new JTextField();
        jLabel7 = new JLabel();
        jFormattedTextFieldValor = new JFormattedTextField();
        jCheckBoxHoje = new JCheckBox();
        jPanel5 = new JPanel();
        jLabel4 = new JLabel();
        jTextFieldNumeroConta = new JTextField();
        jLabel3 = new JLabel();
        jFormattedTextFieldDataVencimento = new JFormattedTextField();
        jLabel1 = new JLabel();
        jTextFieldNumeroEndereco = new JTextField();
        jLabel9 = new JLabel();
        jButtonPagar = new JButton();
        jScrollPane1 = new JScrollPane();
        jTextAreaObservacoes = new JTextArea();
        jLabel8 = new JLabel();

        //======== this ========
        this.setIconImage(new ImageIcon(getClass().getResource("/img/ico.png")).getImage());
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                formWindowClosed(e);
            }
        });
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {

            //======== jPanel2 ========
            {

                //---- jTextFieldPesquisa ----
                jTextFieldPesquisa.addActionListener(e -> jTextFieldPesquisaActionPerformed(e));

                //======== jPanel3 ========
                {

                    //======== jPanel4 ========
                    {

                        //---- jLabel6 ----
                        jLabel6.setText("Data Gerada.:");

                        //---- jFormattedTextFieldDataGerada ----
                        jFormattedTextFieldDataGerada.setEditable(false);

                        //---- jLabel2 ----
                        jLabel2.setText("Data de Pagamento.:");

                        //---- jLabel5 ----
                        jLabel5.setText("S\u00f3cio.:");

                        //---- jTextFieldSocio ----
                        jTextFieldSocio.setEditable(false);

                        //---- jLabel7 ----
                        jLabel7.setText("Valor.:");

                        //---- jFormattedTextFieldValor ----
                        jFormattedTextFieldValor.setEditable(false);

                        //---- jCheckBoxHoje ----
                        jCheckBoxHoje.setText("Hoje");
                        jCheckBoxHoje.addActionListener(e -> jCheckBoxHojeActionPerformed(e));

                        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
                        jPanel4.setLayout(jPanel4Layout);
                        jPanel4Layout.setHorizontalGroup(
                            jPanel4Layout.createParallelGroup()
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel4Layout.createParallelGroup()
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                            .addComponent(jTextFieldSocio, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jFormattedTextFieldValor, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup()
                                                .addComponent(jLabel6)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jCheckBoxHoje)))
                                            .addGap(6, 6, Short.MAX_VALUE)
                                            .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jFormattedTextFieldDataPagamento)
                                                .addComponent(jFormattedTextFieldDataGerada, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))))
                        );
                        jPanel4Layout.setVerticalGroup(
                            jPanel4Layout.createParallelGroup()
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jFormattedTextFieldDataGerada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jFormattedTextFieldDataPagamento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBoxHoje))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldSocio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jFormattedTextFieldValor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        );
                    }

                    GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
                    jPanel3.setLayout(jPanel3Layout);
                    jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(48, Short.MAX_VALUE)
                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                    );
                    jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup()
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                }

                //======== jPanel5 ========
                {

                    //---- jLabel4 ----
                    jLabel4.setText("N\u00famero do Endere\u00e7o.:");

                    //---- jTextFieldNumeroConta ----
                    jTextFieldNumeroConta.setEditable(false);

                    //---- jLabel3 ----
                    jLabel3.setText("Data de Vencimento.:");

                    //---- jFormattedTextFieldDataVencimento ----
                    jFormattedTextFieldDataVencimento.setEditable(false);

                    //---- jLabel1 ----
                    jLabel1.setText("N\u00famero da Conta.:");

                    //---- jTextFieldNumeroEndereco ----
                    jTextFieldNumeroEndereco.setEditable(false);

                    GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
                    jPanel5.setLayout(jPanel5Layout);
                    jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup()
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup()
                                            .addComponent(jTextFieldNumeroEndereco)
                                            .addComponent(jFormattedTextFieldDataVencimento, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextFieldNumeroConta)))
                                .addGap(0, 0, 0))
                    );
                    jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup()
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNumeroConta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup()
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextFieldDataVencimento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldNumeroEndereco, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 10, Short.MAX_VALUE))
                    );
                }

                //---- jLabel9 ----
                jLabel9.setText("Pesquisar");

                GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldPesquisa, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)))
                            .addGap(74, 74, 74)
                            .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup()
                                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldPesquisa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
        }

        //---- jButtonPagar ----
        jButtonPagar.setText("Pagar");
        jButtonPagar.addActionListener(e -> jButtonPagarActionPerformed(e));

        //======== jScrollPane1 ========
        {

            //---- jTextAreaObservacoes ----
            jTextAreaObservacoes.setColumns(20);
            jTextAreaObservacoes.setRows(5);
            jScrollPane1.setViewportView(jTextAreaObservacoes);
        }

        //---- jLabel8 ----
        jLabel8.setText("Observa\u00e7\u00f5es.:");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonPagar, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 560, GroupLayout.PREFERRED_SIZE)))
                    .addGap(21, 21, 21))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(10, 10, 10)
                    .addComponent(jButtonPagar)
                    .addGap(10, 10, 10))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
  
        this.telaPrincipal.setEnabled(true);
        this.telaPrincipal.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
     
        limparCampos();
        if(!jTextFieldPesquisa.getText().equals("")){
            
            Conta c = new DaoContasMensais().ContasPorId(Integer.parseInt(jTextFieldPesquisa.getText()));
            if(c!=null){
                
               jFormattedTextFieldDataVencimento.setText(SimpleDateFormat.getDateInstance().format(c.getDataVence()));
               jTextFieldNumeroConta.setText(String.valueOf(c.getId()));
               
               if(c.getDataVence().before(new Date())){
                   jFormattedTextFieldDataVencimento.setBackground(Color.red);
               }else{
                   jFormattedTextFieldDataVencimento.setBackground(Color.WHITE);
               }
               
               jTextFieldNumeroEndereco.setText(String.valueOf(c.getIdEnderecoPessoa().getNumero()));
               jTextFieldSocio.setText(c.getIdEnderecoPessoa().getIdPessoa().getNome()+" "+c.getIdEnderecoPessoa().getIdPessoa().getSobrenome());
               jFormattedTextFieldDataGerada.setText(SimpleDateFormat.getDateInstance().format(c.getDataGerada()));
               jTextAreaObservacoes.setText(c.getObservacoes());
               
               if(c.getDataPag() != null)
               {
                   jFormattedTextFieldDataPagamento.setEditable(false);
                   jFormattedTextFieldDataPagamento.setText(SimpleDateFormat.getDateInstance().format(c.getDataPag()));
                   jButtonPagar.setEnabled(false);
                  
               }else{
                 //jFormattedTextFieldDataPagamento.setEditable(true);
                 jButtonPagar.setEnabled(true);
               }
               
               double soma = 0;
               
               for(Taxasconta tx : c.getTaxascontaList()){
                   soma += tx.getTaxaid().getValor().doubleValue();
               }
               jFormattedTextFieldValor.setText(String.valueOf(soma));
            }else{
  
                JOptionPane.showMessageDialog(this,"Conta não encontrada","Atenção",JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        }
        
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        
        Pattern p = Pattern.compile("\\d{2}\\/\\d{2}\\/\\d{4}");
        Matcher m = p.matcher(jFormattedTextFieldDataPagamento.getText());
        
        if(m.find()){
        int op = JOptionPane.showConfirmDialog(this,"Confirma o pagamento desta conta?","Atenção",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(op == JOptionPane.YES_OPTION){
        try{
        
        Conta c = new DaoContasMensais().ContasPorId(Integer.parseInt(jTextFieldNumeroConta.getText()));
        c.setDataPag(SimpleDateFormat.getDateInstance().parse(jFormattedTextFieldDataPagamento.getText()));
        c.setObservacoes(jTextAreaObservacoes.getText());
        
        
        new DaoContasMensais().AtualizarConta(c);
        JOptionPane.showMessageDialog(this,"Conta Paga","Atenção",JOptionPane.INFORMATION_MESSAGE);
        limparCampos();
        }catch(NumberFormatException | ParseException | HeadlessException e){
            
            JOptionPane.showMessageDialog(this,"Erro: "+e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }
    }else{
            JOptionPane.showMessageDialog(this,"Data de pagamento é obrigatório","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jCheckBoxHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHojeActionPerformed
        
        String data = new SimpleDateFormat("ddMMyyyy").format(new Date());
        
        if(jCheckBoxHoje.isSelected()){      
            jFormattedTextFieldDataPagamento.setText(data);
            jFormattedTextFieldDataPagamento.setEditable(false);
        }
        else{
            jFormattedTextFieldDataPagamento.setText(null);
            jFormattedTextFieldDataPagamento.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBoxHojeActionPerformed

    private void limparCampos(){
        
        jCheckBoxHoje.setSelected(false);
        jTextFieldNumeroConta.setText("");
        jTextFieldNumeroEndereco.setText("");
        jTextFieldSocio.setText("");
        jTextAreaObservacoes.setText("");
        jFormattedTextFieldDataGerada.setText("");
        jFormattedTextFieldDataPagamento.setText("");
        jFormattedTextFieldValor.setText("");
        jFormattedTextFieldDataVencimento.setText("");
        jButtonPagar.setEnabled(false);
        jFormattedTextFieldDataVencimento.setBackground(Color.WHITE);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GContasAReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GContasAReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GContasAReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GContasAReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GContasAReceber().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField jTextFieldPesquisa;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JLabel jLabel6;
    private JFormattedTextField jFormattedTextFieldDataGerada;
    private JLabel jLabel2;
    private JFormattedTextField jFormattedTextFieldDataPagamento;
    private JLabel jLabel5;
    private JTextField jTextFieldSocio;
    private JLabel jLabel7;
    private JFormattedTextField jFormattedTextFieldValor;
    private JCheckBox jCheckBoxHoje;
    private JPanel jPanel5;
    private JLabel jLabel4;
    private JTextField jTextFieldNumeroConta;
    private JLabel jLabel3;
    private JFormattedTextField jFormattedTextFieldDataVencimento;
    private JLabel jLabel1;
    private JTextField jTextFieldNumeroEndereco;
    private JLabel jLabel9;
    private JButton jButtonPagar;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaObservacoes;
    private JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
