package br.org.acal.application.telas.relatorios;


import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;

import br.org.acal.application.telas.TelaPrincipal;
import br.org.acal.resouces.dao.DaoFuncionario;
import br.org.acal.resouces.entidades.Funcionario;
import br.org.acal.infra.HibernateUtil;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class TelaRelatoriosCheques extends javax.swing.JDialog {

    /**
     * Creates new form TelaRelatoriosCheques
     */
    public TelaRelatoriosCheques(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        travarComponentes();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner non-commercial license
    private void initComponents() {
        jPanel15 = new JPanel();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        jCheckBoxId = new JCheckBox();
        jPanel1 = new JPanel();
        jTextFieldIdMaior = new JTextField();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jTextFieldIdMenor = new JTextField();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jPanel8 = new JPanel();
        jCheckBoxValor = new JCheckBox();
        jPanel4 = new JPanel();
        jTextFieldValorMaior = new JTextField();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        jTextFieldValorMenor = new JTextField();
        jPanel5 = new JPanel();
        jLabel3 = new JLabel();
        jPanel10 = new JPanel();
        jCheckBoxData = new JCheckBox();
        jPanel6 = new JPanel();
        jLabel11 = new JLabel();
        jLabel12 = new JLabel();
        jFormattedTextFieldDataMenor = new JFormattedTextField();
        jFormattedTextFieldDataMaior = new JFormattedTextField();
        jPanel7 = new JPanel();
        jLabel4 = new JLabel();
        jPanel11 = new JPanel();
        jCheckBoxFuncionario = new JCheckBox();
        jPanel9 = new JPanel();
        jComboBoxFuncionario = new JComboBox<>();
        jPanel12 = new JPanel();
        jLabel5 = new JLabel();
        jPanel13 = new JPanel();
        jCheckBoxFavorecido = new JCheckBox();
        jPanel14 = new JPanel();
        jTextFieldFavorecido = new JTextField();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jPanel16 = new JPanel();
        jLabel6 = new JLabel();
        jPanel18 = new JPanel();
        jCheckRegristro = new JCheckBox();
        jCheckOrdernarValor = new JCheckBox();
        jCheckData = new JCheckBox();
        jCheckFuncionario = new JCheckBox();
        jCheckFavorecido = new JCheckBox();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        var contentPane = getContentPane();

        //======== jPanel15 ========
        {
            jPanel15.setBorder(new BevelBorder(BevelBorder.RAISED));

            //======== jPanel3 ========
            {
                jPanel3.setBorder(new EtchedBorder());

                //---- jLabel2 ----
                jLabel2.setText("Regristro");

                //---- jCheckBoxId ----
                jCheckBoxId.setText("Filtrar por Regristro");
                jCheckBoxId.setPreferredSize(new Dimension(100, 23));
                jCheckBoxId.addActionListener(e -> jCheckBoxIdActionPerformed(e));

                //======== jPanel1 ========
                {

                    //---- jTextFieldIdMaior ----
                    jTextFieldIdMaior.addActionListener(e -> jTextFieldIdMaiorActionPerformed(e));

                    //---- jLabel7 ----
                    jLabel7.setText("E");

                    //---- jLabel8 ----
                    jLabel8.setText("Entre");

                    //---- jTextFieldIdMenor ----
                    jTextFieldIdMenor.addActionListener(e -> jTextFieldIdMenorActionPerformed(e));

                    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(97, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(jTextFieldIdMenor, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdMaior, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIdMaior, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldIdMenor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                    );
                }

                GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCheckBoxId, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                );
                jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(54, 54, 54))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxId, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            //======== jPanel2 ========
            {
                jPanel2.setBorder(new EtchedBorder());

                //---- jLabel1 ----
                jLabel1.setText("Valor");

                //======== jPanel8 ========
                {

                    //---- jCheckBoxValor ----
                    jCheckBoxValor.setText("Filtrar por Valor");
                    jCheckBoxValor.setMaximumSize(new Dimension(100, 23));
                    jCheckBoxValor.setMinimumSize(new Dimension(100, 23));
                    jCheckBoxValor.setPreferredSize(new Dimension(100, 23));
                    jCheckBoxValor.addActionListener(e -> jCheckBoxValorActionPerformed(e));

                    GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
                    jPanel8.setLayout(jPanel8Layout);
                    jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBoxValor, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    );
                    jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup()
                            .addComponent(jCheckBoxValor, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    );
                }

                //======== jPanel4 ========
                {

                    //---- jTextFieldValorMaior ----
                    jTextFieldValorMaior.addActionListener(e -> jTextFieldValorMaiorActionPerformed(e));

                    //---- jLabel9 ----
                    jLabel9.setText("E");

                    //---- jLabel10 ----
                    jLabel10.setText("Entre");

                    //---- jTextFieldValorMenor ----
                    jTextFieldValorMenor.addActionListener(e -> jTextFieldValorMenorActionPerformed(e));

                    GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
                    jPanel4.setLayout(jPanel4Layout);
                    jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(97, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldValorMenor, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValorMaior, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                    );
                    jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldValorMaior, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldValorMenor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                    );
                }

                GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel1)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(54, 54, 54))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            //======== jPanel5 ========
            {
                jPanel5.setBorder(new EtchedBorder());

                //---- jLabel3 ----
                jLabel3.setText("Data");

                //======== jPanel10 ========
                {

                    //---- jCheckBoxData ----
                    jCheckBoxData.setText("Filtrar por Data");
                    jCheckBoxData.setMaximumSize(new Dimension(100, 23));
                    jCheckBoxData.setMinimumSize(new Dimension(100, 23));
                    jCheckBoxData.setPreferredSize(new Dimension(100, 23));
                    jCheckBoxData.addActionListener(e -> jCheckBoxDataActionPerformed(e));

                    GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
                    jPanel10.setLayout(jPanel10Layout);
                    jPanel10Layout.setHorizontalGroup(
                        jPanel10Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBoxData, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    );
                    jPanel10Layout.setVerticalGroup(
                        jPanel10Layout.createParallelGroup()
                            .addComponent(jCheckBoxData, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    );
                }

                //======== jPanel6 ========
                {

                    //---- jLabel11 ----
                    jLabel11.setText("E");

                    //---- jLabel12 ----
                    jLabel12.setText("Entre");

                    GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
                    jPanel6.setLayout(jPanel6Layout);
                    jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(jFormattedTextFieldDataMenor, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldDataMaior, GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addGap(35, 35, 35))
                    );
                    jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jFormattedTextFieldDataMenor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldDataMaior, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                    );
                }

                GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel3)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGap(54, 54, 54))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup()
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            //======== jPanel7 ========
            {
                jPanel7.setBorder(new EtchedBorder());

                //---- jLabel4 ----
                jLabel4.setText("Funcionario");

                //======== jPanel11 ========
                {

                    //---- jCheckBoxFuncionario ----
                    jCheckBoxFuncionario.setText("Filtrar por Funcionario");
                    jCheckBoxFuncionario.setMaximumSize(new Dimension(100, 23));
                    jCheckBoxFuncionario.setMinimumSize(new Dimension(100, 23));
                    jCheckBoxFuncionario.setPreferredSize(new Dimension(100, 23));
                    jCheckBoxFuncionario.addActionListener(e -> jCheckBoxFuncionarioActionPerformed(e));

                    GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
                    jPanel11.setLayout(jPanel11Layout);
                    jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBoxFuncionario, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    );
                    jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup()
                            .addComponent(jCheckBoxFuncionario, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                }

                //======== jPanel9 ========
                {

                    //---- jComboBoxFuncionario ----
                    jComboBoxFuncionario.setModel(new DefaultComboBoxModel<>(new String[] {

                    }));

                    GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
                    jPanel9.setLayout(jPanel9Layout);
                    jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup()
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBoxFuncionario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(107, Short.MAX_VALUE))
                    );
                    jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxFuncionario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                    );
                }

                GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                    jPanel7Layout.createParallelGroup()
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel4)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                );
                jPanel7Layout.setVerticalGroup(
                    jPanel7Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addGap(54, 54, 54))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            //======== jPanel12 ========
            {
                jPanel12.setBorder(new EtchedBorder());

                //---- jLabel5 ----
                jLabel5.setText("Favorecido");

                //======== jPanel13 ========
                {

                    //---- jCheckBoxFavorecido ----
                    jCheckBoxFavorecido.setText("Filtrar por Favorecido");
                    jCheckBoxFavorecido.setMaximumSize(new Dimension(100, 23));
                    jCheckBoxFavorecido.setMinimumSize(new Dimension(100, 23));
                    jCheckBoxFavorecido.setPreferredSize(new Dimension(100, 23));
                    jCheckBoxFavorecido.addActionListener(e -> jCheckBoxFavorecidoActionPerformed(e));

                    GroupLayout jPanel13Layout = new GroupLayout(jPanel13);
                    jPanel13.setLayout(jPanel13Layout);
                    jPanel13Layout.setHorizontalGroup(
                        jPanel13Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jCheckBoxFavorecido, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                    );
                    jPanel13Layout.setVerticalGroup(
                        jPanel13Layout.createParallelGroup()
                            .addComponent(jCheckBoxFavorecido, GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    );
                }

                //======== jPanel14 ========
                {

                    GroupLayout jPanel14Layout = new GroupLayout(jPanel14);
                    jPanel14.setLayout(jPanel14Layout);
                    jPanel14Layout.setHorizontalGroup(
                        jPanel14Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextFieldFavorecido, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addContainerGap())
                    );
                    jPanel14Layout.setVerticalGroup(
                        jPanel14Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(jTextFieldFavorecido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                    );
                }

                GroupLayout jPanel12Layout = new GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                    jPanel12Layout.createParallelGroup()
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel5)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                );
                jPanel12Layout.setVerticalGroup(
                    jPanel12Layout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(25, 25, 25))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                );
            }

            //---- jButton3 ----
            jButton3.setText("Hoje");
            jButton3.addActionListener(e -> jButton3ActionPerformed(e));

            //---- jButton4 ----
            jButton4.setText("Gerar");
            jButton4.addActionListener(e -> jButton4ActionPerformed(e));

            //======== jPanel16 ========
            {
                jPanel16.setBorder(new EtchedBorder());
                jPanel16.setPreferredSize(new Dimension(486, 50));

                //---- jLabel6 ----
                jLabel6.setText("Ordernar");

                //======== jPanel18 ========
                {

                    //---- jCheckRegristro ----
                    jCheckRegristro.setText("Regristro");
                    jCheckRegristro.addActionListener(e -> jCheckRegristroActionPerformed(e));

                    //---- jCheckOrdernarValor ----
                    jCheckOrdernarValor.setText("Valor");
                    jCheckOrdernarValor.addActionListener(e -> jCheckOrdernarValorActionPerformed(e));

                    //---- jCheckData ----
                    jCheckData.setText("Data");
                    jCheckData.addActionListener(e -> jCheckDataActionPerformed(e));

                    //---- jCheckFuncionario ----
                    jCheckFuncionario.setText("Funcionario");
                    jCheckFuncionario.addActionListener(e -> jCheckFuncionarioActionPerformed(e));

                    //---- jCheckFavorecido ----
                    jCheckFavorecido.setText("Despeza");
                    jCheckFavorecido.addActionListener(e -> jCheckFavorecidoActionPerformed(e));

                    GroupLayout jPanel18Layout = new GroupLayout(jPanel18);
                    jPanel18.setLayout(jPanel18Layout);
                    jPanel18Layout.setHorizontalGroup(
                        jPanel18Layout.createParallelGroup()
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckRegristro, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jCheckOrdernarValor, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckData, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jCheckFuncionario, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(jCheckFavorecido, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64))
                    );
                    jPanel18Layout.setVerticalGroup(
                        jPanel18Layout.createParallelGroup()
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel18Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckRegristro)
                                    .addComponent(jCheckOrdernarValor)
                                    .addComponent(jCheckData)
                                    .addComponent(jCheckFuncionario)
                                    .addComponent(jCheckFavorecido))
                                .addContainerGap(19, Short.MAX_VALUE))
                    );
                }

                GroupLayout jPanel16Layout = new GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                    jPanel16Layout.createParallelGroup()
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel18, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel16Layout.setVerticalGroup(
                    jPanel16Layout.createParallelGroup()
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jPanel18, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
            }

            GroupLayout jPanel15Layout = new GroupLayout(jPanel15);
            jPanel15.setLayout(jPanel15Layout);
            jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup()
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel15Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel16, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup()
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel15, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel15, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        pack();
        setLocationRelativeTo(getOwner());

        //======== jScrollPane1 ========
        {

            //---- jTextArea1 ----
            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIdActionPerformed

        if(jCheckBoxId.isSelected()){
            jTextFieldIdMaior.setEditable(true);
            jTextFieldIdMenor.setEditable(true);
        }
        else
        {
            jTextFieldIdMaior.setText("");
            jTextFieldIdMenor.setText("");
            jTextFieldIdMaior.setEditable(false);
            jTextFieldIdMenor.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxIdActionPerformed

    private void jTextFieldIdMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdMaiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdMaiorActionPerformed

    private void jTextFieldIdMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdMenorActionPerformed

    private void jCheckBoxValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxValorActionPerformed

        if(jCheckBoxValor.isSelected()){
            jTextFieldValorMaior.setEditable(true);
            jTextFieldValorMenor.setEditable(true);
        }
        else
        {
            jTextFieldValorMaior.setText("");
            jTextFieldValorMenor.setText("");
            jTextFieldValorMaior.setEditable(false);
            jTextFieldValorMenor.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxValorActionPerformed

    private void jTextFieldValorMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorMaiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorMaiorActionPerformed

    private void jTextFieldValorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorMenorActionPerformed

    private void jCheckBoxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDataActionPerformed

        if(jCheckBoxData.isSelected()){
            jFormattedTextFieldDataMaior.setEditable(true);
            jFormattedTextFieldDataMenor.setEditable(true);
        }
        else
        {
            //   SimpleDateFormat.getDateInstance().parse(jFormattedTextFieldDataMaior.getText());
            jFormattedTextFieldDataMaior.setText("");
            jFormattedTextFieldDataMenor.setText("");
            jFormattedTextFieldDataMaior.setEditable(false);
            jFormattedTextFieldDataMenor.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxDataActionPerformed

    private void jCheckBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFuncionarioActionPerformed

        if(jCheckBoxFuncionario.isSelected()){
            jComboBoxFuncionario.setEnabled(true);

            if(jComboBoxFuncionario.getItemCount()==0){
                jComboBoxFuncionario.addItem("");
                List<Funcionario> f = new DaoFuncionario().BuscarFuncionarios();
                for(Funcionario funcs: f){
                    jComboBoxFuncionario.addItem(funcs.getIdPessoa().getNome() +" "+ funcs.getIdPessoa().getSobrenome());
                }
            }

        }
        else{
            jComboBoxFuncionario.setEnabled(false);
            jComboBoxFuncionario.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jCheckBoxFuncionarioActionPerformed

    private void jCheckBoxFavorecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFavorecidoActionPerformed
        if(jCheckBoxFavorecido.isSelected()){
            jTextFieldFavorecido.setEditable(true);
        }
        else
        {
            jTextFieldFavorecido.setText(null);
            jTextFieldFavorecido.setEditable(false);
        }
    }//GEN-LAST:event_jCheckBoxFavorecidoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(
            preencidoCheckBox(jCheckBoxId,jTextFieldIdMenor.getText(),jTextFieldIdMaior.getText())            &&
            preencidoCheckBox(jCheckBoxData,jFormattedTextFieldDataMenor.getText().replaceAll("[\\/\\s]",""),jFormattedTextFieldDataMaior.getText().replaceAll("[\\/\\s]",""))   &&
            preencidoCheckBox(jCheckBoxValor,jTextFieldValorMenor.getText(),jTextFieldValorMaior.getText())   &&
            preencidoCombobox(jCheckBoxFavorecido, jTextFieldFavorecido.getText())                      &&
            preencidoCombobox(jCheckBoxFuncionario, (String) jComboBoxFuncionario.getSelectedItem())
        )
        {
            new Thread() {
                @Override
                @SuppressWarnings("empty-statement")
                public void run() {

                    int cont = 0;
                    int and = 0;

                    final String where= " where ";
                    String idMenor     = null;
                    String idMaior     = null;
                    String valMenor    = null;
                    String valMaior    = null;
                    String datMenor    = null;
                    String funcionario = null;
                    String favorecido  = null;
                    String datMaior    = null;
                    String sql         = "";

                    if(jCheckBoxId.isSelected()){
                        idMenor =  " ( c.id between " + jTextFieldIdMenor.getText()  ;
                        idMaior =  " and  "+ jTextFieldIdMaior.getText() +" ) ";
                        cont ++;
                    }
                    if(jCheckBoxValor.isSelected())
                    {
                        valMenor =  " ( c.valor between " + jTextFieldValorMenor.getText()  ;
                        valMaior =  " and  "+ jTextFieldValorMaior.getText() +" ) ";

                        cont ++;
                    }

                    if(jCheckBoxData.isSelected()){

                        String[] dataMenor = jFormattedTextFieldDataMenor.getText().split("/");

                        datMenor =  " ( c.dataVencimento between '" + dataMenor[2]+"/"+dataMenor[1]+"/"+dataMenor[0] +"'";
                        String[] dataMaior = jFormattedTextFieldDataMaior.getText().split("/");
                        datMaior =  " and  '"+  dataMaior[2]+"/"+dataMaior[1]+"/"+dataMaior[0] + "' ) ";
                        cont ++;
                    }
                    if(jCheckBoxFuncionario.isSelected())
                    {
                        funcionario =  "(trim((concat(p.nome,\" \",p.sobrenome))) = trim('"+jComboBoxFuncionario.getSelectedItem() +"'))"  ;
                        cont ++;
                    }
                    if(jCheckBoxFavorecido.isSelected())
                    {
                        favorecido = "(m.nome like '%"+jTextFieldFavorecido.getText() +"%')" ;
                     // favorecido =  "((concat(p.nome,\" \",p.sobrenome)) like %"+ jTextFieldFavorecido.getText() +"%   )    "  ;
                        cont ++;
                    }

                    if(cont>=1){sql = where;}

                    if(jCheckBoxId.isSelected()){

                        if(
                            (jCheckBoxValor.isSelected()      ||
                                jCheckBoxData.isSelected()       ||
                                jCheckBoxFuncionario.isSelected()||
                                jCheckBoxFavorecido.isSelected())
                            &&(and != 0)  ){
                            sql += " and ";
                        }
                        else{and++;}
                        sql += idMenor + idMaior;
                    }

                    if(jCheckBoxValor.isSelected())     {
                        if(
                            (jCheckBoxId.isSelected()      ||
                                jCheckBoxData.isSelected()       ||
                                jCheckBoxFuncionario.isSelected()||
                                jCheckBoxFavorecido.isSelected())
                            &&(and != 0)  ){
                            sql += " and ";
                        }
                        else{and++;}
                        sql += valMenor + valMaior;
                    }

                    if(jCheckBoxData.isSelected())
                    {
                        if(
                            (jCheckBoxValor.isSelected()      ||
                                jCheckBoxId.isSelected()       ||
                                jCheckBoxFuncionario.isSelected()||
                                jCheckBoxFavorecido.isSelected())
                            &&(and != 0)  ){
                            sql += " and ";
                        }
                        else{and++;}
                        sql += datMenor + datMaior;
                    }
                    if(jCheckBoxFuncionario.isSelected())
                    {
                        if(
                            (jCheckBoxValor.isSelected()      ||
                                jCheckBoxId.isSelected()       ||
                                jCheckBoxValor.isSelected()||
                                jCheckBoxFavorecido.isSelected())
                            &&(and != 0)  ){
                            sql += " and ";
                        }
                        else{and++;}
                        sql += funcionario;
                    }

                    if(jCheckBoxFavorecido.isSelected())
                    {
                        if(
                            (jCheckBoxValor.isSelected()      ||
                                jCheckBoxId.isSelected()       ||
                                jCheckBoxValor.isSelected()||
                                jCheckBoxFuncionario.isSelected())
                            &&(and != 0)  ){
                            sql += " and ";
                        }
                        else{and++;}
                        sql += favorecido;
                    }

                    if     (jCheckRegristro.isSelected())    {sql += " order by c.id";         cont++;}
                    else if(jCheckOrdernarValor.isSelected()){sql += " order by c.valor";      cont++;}
                    else if(jCheckData.isSelected())         {sql += " order by c.dataVencimento";cont++;}
                    else if(jCheckFuncionario.isSelected())  {sql += " order by p.nome";       cont++;}
                    else if(jCheckFavorecido.isSelected())   {sql += " order by m.nome";         cont++;}

                    System.out.println(sql);
                    try {
                        Connection conn = HibernateUtil.getConnection();
                        Map<String, Object> p = new HashMap<>();

                        if(cont==0){p.put("complementos","");}
                        else       {p.put("complementos",sql);}
                        JasperPrint jasper = JasperFillManager.fillReport(getClass().getResourceAsStream("/relatorios/rc_cheques.jasper"), p, conn);
                        JasperViewer.viewReport(jasper, false);

                    } catch (Exception ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"você deve preencer corretamente os campos escolhidos");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckRegristroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRegristroActionPerformed

        jCheckData.setSelected(false);
        jCheckFavorecido.setSelected(false);
        jCheckFuncionario.setSelected(false);
        jCheckOrdernarValor.setSelected(false);
    }//GEN-LAST:event_jCheckRegristroActionPerformed

    private void jCheckOrdernarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckOrdernarValorActionPerformed
        jCheckRegristro.setSelected(false);
        jCheckData.setSelected(false);
        jCheckFavorecido.setSelected(false);
        jCheckFuncionario.setSelected(false);
    }//GEN-LAST:event_jCheckOrdernarValorActionPerformed

    private void jCheckDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDataActionPerformed

        jCheckRegristro.setSelected(false);
        jCheckFavorecido.setSelected(false);
        jCheckFuncionario.setSelected(false);
        jCheckOrdernarValor.setSelected(false);
    }//GEN-LAST:event_jCheckDataActionPerformed

    private void jCheckFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFuncionarioActionPerformed
        jCheckRegristro.setSelected(false);
        jCheckData.setSelected(false);
        jCheckFavorecido.setSelected(false);
        jCheckOrdernarValor.setSelected(false);
    }//GEN-LAST:event_jCheckFuncionarioActionPerformed

    private void jCheckFavorecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFavorecidoActionPerformed
        jCheckRegristro.setSelected(false);
        jCheckData.setSelected(false);
        jCheckFuncionario.setSelected(false);
        jCheckOrdernarValor.setSelected(false);
    }//GEN-LAST:event_jCheckFavorecidoActionPerformed
    private Funcionario Filtra(String nome)
    {
     Funcionario f = new DaoFuncionario().BuscarFuncionario(nome);
        System.out.println("dao funcionario voltou " + f);
     return f;
    }
     public boolean preencidoCombobox(JCheckBox check, String string)
    {
      boolean test;
      if(check.isSelected()){
        if(!string.equals("")){
        test= true;
        }
        else{
        test =false;
        }
      }
      else{
      test = true;
      }
      return test;
    }
    public boolean preencidoCheckBox(JCheckBox check,String a,String b){
       boolean test;
        
        if(check.isSelected()){
            if(!a.equals("")&& !b.equals("")){
            test = true;
            }
            else{
            test= false;
            }
        }
        else
        {
        test = true;
        }
        return test;
    }
     
    public void travarComponentes()
    {
     jTextFieldValorMenor.setEditable(false);
     jTextFieldValorMaior.setEditable(false);
     jTextFieldIdMenor.setEditable(false);
     jTextFieldIdMaior.setEditable(false);
     jFormattedTextFieldDataMenor.setEditable(false);
     jFormattedTextFieldDataMaior.setEditable(false);
     jComboBoxFuncionario.setEnabled(false);
     jTextFieldFavorecido.setEditable(false);
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaRelatoriosCheques.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(TelaRelatoriosCheques.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TelaRelatoriosCheques.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TelaRelatoriosCheques.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaRelatoriosCheques dialog = new TelaRelatoriosCheques(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner non-commercial license
    private JPanel jPanel15;
    private JPanel jPanel3;
    private JLabel jLabel2;
    private JCheckBox jCheckBoxId;
    private JPanel jPanel1;
    private JTextField jTextFieldIdMaior;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JTextField jTextFieldIdMenor;
    private JPanel jPanel2;
    private JLabel jLabel1;
    private JPanel jPanel8;
    private JCheckBox jCheckBoxValor;
    private JPanel jPanel4;
    private JTextField jTextFieldValorMaior;
    private JLabel jLabel9;
    private JLabel jLabel10;
    private JTextField jTextFieldValorMenor;
    private JPanel jPanel5;
    private JLabel jLabel3;
    private JPanel jPanel10;
    private JCheckBox jCheckBoxData;
    private JPanel jPanel6;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JFormattedTextField jFormattedTextFieldDataMenor;
    private JFormattedTextField jFormattedTextFieldDataMaior;
    private JPanel jPanel7;
    private JLabel jLabel4;
    private JPanel jPanel11;
    private JCheckBox jCheckBoxFuncionario;
    private JPanel jPanel9;
    private JComboBox<String> jComboBoxFuncionario;
    private JPanel jPanel12;
    private JLabel jLabel5;
    private JPanel jPanel13;
    private JCheckBox jCheckBoxFavorecido;
    private JPanel jPanel14;
    private JTextField jTextFieldFavorecido;
    private JButton jButton3;
    private JButton jButton4;
    private JPanel jPanel16;
    private JLabel jLabel6;
    private JPanel jPanel18;
    private JCheckBox jCheckRegristro;
    private JCheckBox jCheckOrdernarValor;
    private JCheckBox jCheckData;
    private JCheckBox jCheckFuncionario;
    private JCheckBox jCheckFavorecido;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
